version: 2
jobs:
  deploy_branch:  # deploys a branch from GH to DH
    docker:
      - image: 'redislabsmodules/rmbuilder:latest'
    steps:
      - checkout
      - run:  # until rmbuild includes it
          name: Install local docker client
          command: |
            VER="18.03.1-ce"
            wget -O /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker container
          command: docker build -t redislabs/redismod:$CIRCLE_BRANCH .
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push redislabs/redismod:$CIRCLE_BRANCH
  deploy_release: # deploys a release from GH to DH
    docker:
      - image: 'redislabsmodules/rmbuilder:latest'
    steps:
      - checkout
      - run:  # until rmbuild includes it
          name: Install local docker client
          command: |
            VER="18.03.1-ce"
            wget -O /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker container
          command: docker build -t redislabs/redismod:$CIRCLE_TAG .
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push redislabs/redismod:$CIRCLE_TAG
  deploy_latest:  # deploys GH master as DH latest
    docker:
      - image: 'redislabsmodules/rmbuilder:latest'
    steps:
      - checkout
      - run:  # until rmbuild includes it
          name: Install local docker client
          command: |
            VER="18.03.1-ce"
            wget -O /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker container
          command: docker build -t redislabs/redismod:latest .
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push redislabs/redismod:latest
workflows:
  version: 2
  deploy:
    jobs:
      - deploy_latest:
        filters:
          branches:
            only: master
      - deploy_release:
        filters:
          tags:
             only: '/^v[0-9].*/'
      - deploy_branch:
        filters:
          branches:
            ignore: master